### ISSUE TITLE
Reaper sim is broken

### ISSUE THREAD

**Issue by Hapseleg** [xiv-gear-planner/gear-planner#394]
Hi,

It seems theres a js function thats broken, it simply says _error_ at rpr sim dps

```
Sim Error! TypeError: rprAbility.updateShroudGauge is not a function
    at RprCycleProcessor.use (rpr_sheet_sim.ts:133:28)
    at RprCycleProcessor.useGcd (cycle_sim.ts:1215:21)
    at RprCycleProcessor.useOpener (rpr_sheet_sim.ts:223:14)
    at Object.apply (rpr_sheet_sim.ts:449:20)
    at sim_processors.ts:149:17
    at Array.map (<anonymous>)
    at RprSheetSim.generateRotations (sim_processors.ts:138:26)
    at RprSheetSim.simulate (sim_processors.ts:195:47)
    at sheet.ts:715:37
```

Thanks for the great site :) <3

**Comment by xpdota** [comment]
Fixed in #397
